#!/bin/sh
SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"

rm -rf ${SCRIPT_DIR}/html
rm -rf ${SCRIPT_DIR}/docset
rm -rf ${SCRIPT_DIR}/publish

appledoc \
  \
  --publish-docset \
  --keep-intermediate-files \
  --no-install-docset \
  --keep-undocumented-objects \
  --keep-undocumented-members \
  --no-repeat-first-par \
  --no-warn-undocumented-object \
  --no-warn-undocumented-member \
  \
  --project-name    BBBootstrap \
  --project-company BiasedBit \
  --company-id      com.biasedbit \
  --ignore          .m \
  --output          ${SCRIPT_DIR} \
  \
  ${SCRIPT_DIR}/../Classes
